name: phase_coding_snn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - absl-py
      - annotated-types
      - astunparse
      - blosc2
      - certifi
      - cffi
      - charset-normalizer
      - contourpy
      - cryptography
      - cycler
      - filelock
      - flatbuffers
      - fonttools
      - fsspec
      - gast
      - google-auth
      - google-auth-oauthlib
      - google-pasta
      - grpcio
      - h5py
      - idna
      - jinja2
      - keras
      - kiwisolver
      - libclang
      - markdown
      - matplotlib
      - ml-dtypes
      - mpmath
      - msgpack
      - networkx
      - numexpr
      - numpy
      - oauthlib
      - opt-einsum
      - pillow
      - protobuf
      - pyasn1
      - pyasn1-modules
      - pycparser
      - pydantic
      - pygments
      - pyparsing
      - python-dateutil
      - requests
      - requests-oauthlib
      - rich
      - scipy
      - setuptools
      - six
      - sympy
      - tables
      - tensorboard
      - tensorflow
      - termcolor
      - threadpoolctl
      - torch
      - torchvision
      - typing-extensions
      - urllib3
      - werkzeug
      - wrapt